spring:
- application:
    - name: Dress
- datasource:
    - url: jdbc:mysql://localhost:3306/yaml?createDatabaseIfNotExist=true
    - username: root
    - password: 1234
- jpa:
    - hibernate: 
      - ddl-auto: update
    - properties: 
      - hibernate:
        - format_sql: true
        - dialect: org.hibernate.dialect.MySQL8Dialect